package game_of_life;

public enum Pattern {
    BLINKER,
    TOAD,
    BEACON,
    PULSAR,
    PENTADECATHLON,
    GLIDER,
    LIGHTWEIGHT_SPACESHIP,
    MIDDLEWEIGHT_SPACESHIP,
    HEAVYWEIGHT_SPACESHIP
}
